version: '3.8'

services:
  vpn-frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge
